using System;

/*
 * Copyright (c) 1996, 2004, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

namespace java.rmi.server
{

	/// <summary>
	/// This exception is thrown when a call is received that does not
	/// match the available skeleton.  It indicates either that the
	/// remote method names or signatures in this interface have changed or
	/// that the stub class used to make the call and the skeleton
	/// receiving the call were not generated by the same version of
	/// the stub compiler (<code>rmic</code>).
	/// 
	/// @author  Roger Riggs
	/// @since   JDK1.1 </summary>
	/// @deprecated no replacement.  Skeletons are no longer required for remote
	/// method calls in the Java 2 platform v1.2 and greater. 
	[Obsolete("no replacement.  Skeletons are no longer required for remote")]
	public class SkeletonMismatchException : RemoteException
	{

		/* indicate compatibility with JDK 1.1.x version of class */
		private new const long SerialVersionUID = -7780460454818859281L;

		/// <summary>
		/// Constructs a new <code>SkeletonMismatchException</code> with
		/// a specified detail message.
		/// </summary>
		/// <param name="s"> the detail message
		/// @since JDK1.1 </param>
		/// @deprecated no replacement 
		[Obsolete("no replacement")]
		public SkeletonMismatchException(String s) : base(s)
		{
		}

	}

}